language: bash

services:
  - docker

before_install:
  - docker build -t coldsync .

script:
  - docker run --rm -i -t coldsync sh -c "pip install .[testing] && python setup.py test"

after_success:
  - coveralls

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
