language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pip install .[testing]
  - python setup.py test